config/routes.rb
Wherewerewe::Application.routes.draw do

  get 'log_in' => 'sessions#new', :as => :log_in
  get 'log_out' => 'sessions#destroy', :as => :log_out
  get 'sign_up' => 'users#new', :as => :sign_up

  resources :progressions, :only => [:index]
  resources :series, :only => [:index, :show]
  resources :sessions, :only => [:create, :destroy]
  resources :users, :only => [:create]
  resources :viewings, :only => [:create, :update]

  root :to => 'sessions#new'

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Series.order("name")
  end

  def show
    @series = Series.find params[:id]
  end
end

app/views/series/index.html.haml
%header.page-header
  %h1 series
- @series.each do |s|
  %section.well
    %h2= s.name
    %p= s.overview
    - if current_user && !Viewing.viewings_exist(user_id: current_user.id, series_id: s.id)
      = form_tag(viewings_path) do
        = hidden_field_tag 'series_id', s.id
        = submit_tag 'Add to viewing list', class: 'btn'

app/views/series/show.html.haml
%header.page-header
  %h1= @series.name
.tabbable.tabs-left
  %ul.nav.nav-tabs
    %li
      %a{ href: '#series-overview' } series overview
    - @series.seasons.order("number").each do |s|
      %li{ class: 'active' }
        %a{ href: '#season-' }= "Season #{s.number}"
  .tab-content
    #series-overview.tab-pane
    - @series.seasons.order("number").each do |s|
      #season-.tab-pane.active
        %ol{ class: 'unstyled' }
          - s.episodes.order("number").each do |e|
            %li
              %section#episode{ :class => (e.watched?(current_user) ? "watched" : "") }
                %h3= e.name