config/routes.rb
Wherewerewe::Application.routes.draw do

  get 'log_in' => 'sessions#new', :as => :log_in
  get 'log_out' => 'sessions#destroy', :as => :log_out
  get 'sign_up' => 'users#new', :as => :sign_up

  resources :progressions, :only => [:index]
  resources :series, :only => [:index, :show]
  resources :sessions, :only => [:create, :destroy]
  resources :users, :only => [:create]
  resources :viewings, :only => [:create, :update]

  root :to => 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wherewerewe</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
<!--[%f lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]--
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
%html.no-js{ :lang => "en" }
  <!--<![endif]-->
  %head
    %meta{ :charset => "utf-8" }
    %meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }

    %title where were we
    %meta{ :name => "description", :content => "Keep track of how much of a series you've watched" }
    %meta{ :name => "author", :content => "Mark Scholtz" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    = stylesheet_link_tag "application"

    -# = javascript_include_tag "modernizr"

    = csrf_meta_tag

  %body
    <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{ type: 'button', 'data-toggle' => 'collapse', 'data-target' => '.nav-collapse' }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'where were we', root_path, class: 'brand'
          .nav-collapse.collapse
            %ul.nav
              %li{ class: params[:controller] == 'progressions' ? 'active' : '' }
                = link_to 'progress', progressions_path
              %li{ class: params[:controller] == 'series' ? 'active' : '' }
                = link_to 'search', series_index_path
              - if current_user
                %li
                  = link_to 'log out', log_out_path

    .container

      - unless flash.empty?
        .notifications
          %ul
            - flash.each do |key, message|
              = content_tag :li, message, :id => key

      = yield

    %script{ :src => "//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" }
    :javascript
      window.jQuery || document.write('#{escape_javascript(javascript_include_tag "jquery")}')

    = javascript_include_tag "application"
    :javascript
      var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));